# Default values for orchestrator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

scylladb:
  image:
    repository: gcmcnutt/docker-scylladb

    # TODO this should be provided by, say, gradle driver
    tag: gmcnutt-0.8.6-SNAPSHOT

  config:
    overprovisioned: 1
    maxIORequests: 256
    batchSizeWarnKb: 50
    batchSizeFailKb: 70
    blockedReactorNotifyMs: 7000
    writeRequestTimeoutMs: 7000
#    cpu: 1
#    memory: 500M

  service:
    cqlNativePort: 9042
    thriftPort: 9160
    internodePort: 7000
    jmxPort: 7199
    scyllaRestPort: 10000
    prometheusPort: 9180

    probeTimeoutSeconds: 10
    initialDelaySeconds: 30

  resources: {}

kairosdb:
  image:
    repository: gcmcnutt/docker-kairosdb

    # TODO this should be provided by, say, gradle driver
    tag: gmcnutt-0.8.6-SNAPSHOT

#    datastoreReplicationFactor: 1
#
#    # quote these... https://github.com/kubernetes/helm/blob/master/docs/chart_best_practices/values.md
#    memoryQueueSize: "200000"
#    defaultTtl: "3024000"
#    queueProcessor: org.kairosdb.core.queue.FileQueueProcessor
#    queryThreads: 20

  connectLocalDB: true

  service:
    name: kairosdb
    type: NodePort
    externalPort: 8080
    internalPort: 8080
    probeTimeoutSeconds: 5
    initialDelaySeconds: 30

  resources: {}

persistence:
  ## If defined, volume.beta.kubernetes.io/storage-class: <storageClass>
  ## Default: volume.alpha.kubernetes.io/storage-class: default
  ##
  # storageClass:
  accessMode: ReadWriteOnce
  # if set, a PVC will also be allocated
  # size: 1Gi

global:
  image:
    repositoryPrefix:
    pullPolicy: IfNotPresent
